### ISSUE TITLE
Dynamic `require` in VrpcAdapter.js breaks webpack 5

### ISSUE THREAD

**Issue by cstim** [heisenware/vrpc#36]
**Describe the Bug**
In vrpc/VrpcAdapter.js, Line 109 in the function VrpcAdapter.register( ) a `register` call is made with some variable arguments. However, when including vrpc in a front-end app (e.g. a React app) and letting this being packed by webpack, the webpack tool complaints loudly about this dynamic `require`. This complaint is because webpack surely doesn't know which files need to be bundled and sent to the browser.

Actually this causes webpack v5 to go to every single file trying to setup modules for it before checking which ones are actually being used. Some of those files are not in javascript (some are in python, some in cpp, there are LICENSE files and bash files that execute javascript). A side-effect symptom is that the loading time of the React app are now on the order of ~30 seconds.

This has been the case since approx. October and react-scrips also mentioned that as a warning since then.

**Steps To Reproduce**

1. Run the react-app that includes a dependency to vrpc
2. Observe the following warning 
```
./node_modules/vrpc/vrpc/VrpcAdapter.js
Critical dependency: the request of a dependency is an expression
```

**Expected Behavior**
There shouldn't be such a warning. And the webpack tool shouldn't encounter a dynamic `require` call.

Ideally that whole VrpcAdapter.register() feature needs to be separated into some other file which is not loaded at all when using vrpc from such a react-app, like "VrpcAdapterRegistration.js" or something like that. 
Our frontend colleague suspects that any frontend app will encounter this issue and will want to avoid dealing with the dynamic require calls.

**Comment by bheisen** [comment]
Thanks for reporting this. I as well encountered the warning and wasn't sure about its origin. That's clearly something to be urgently fixed as especially CI tools will immediately error-out as compilation warnings are typically escalated to errors.

The issue will be worked on with high priority.

**Comment by cstim** [comment]
As we were discussing this for the Connectware, we saw that the problem with the dynamic `require` is a problem only in the frontend. The usage of that feature, on the other hand, is only in the backend (the protocol-mapper, as you remember). So one solution here would be to separate it out of the main VrpcAdapter class into something that can be `require`-d in the backend but not in the frontend.

**Comment by filipomar** [comment]
To add more information, as we are updating the front-end bundler, the new Webpack v5 has found some issues regarding vrpc that required custom configuration.

**Dealing with the dynamic resolver**
The bundler will go through all the dependencies referenced by the entry point file (usually `src/index.js`) and attempt to bundle every referenced file into N output files on the created bundle.

Therefore the dynamic resolver should not work on the frontend, as the dynamic files will never be loaded there.
Due to the dynamic [resolver](https://github.com/heisenware/vrpc/blob/432fdbbdd71481640db8d2c9887b87dbf74da136/vrpc/VrpcAdapter.js#L109) though, webpack will try then to load every file (included python scripts on other misc files), in order to, I think, achieve the least amount of module-not-found-failures.

To fix this, I had to add this custom [webpack v5 resolver rule](https://webpack.js.org/configuration/module/#modulerules):
```javascript
{
     /**
     * if vrpc, ignore non js/jsx files
     */
    test: { and: [/(node_modules\/vrpc)/i, { not: [/\.(js|jsx)$/] }] },
    loader: 'ignore-loader'
}
```
Before, the react-scripts would just ignore the errors when loading files, and use only js files that were successfully parsed.

**Fallbacks and global definitions**

I also noticed some references to node core libraries/classes, such as `os`, `fs`, `Buffer` and `path`.
The react-scripts bundler pre-loaded these into the outputted bundle which omitted any errors.
As Webpack removes the kid bicycle wheels, I had to add these configurations:

[Fallback configuration](https://webpack.js.org/configuration/resolve/#resolvefallback), so I can tell webpack to load my browserfied alternatives instead of telling me `os` is not compatible with frontend.

```javascript
{
    os: require.resolve("os-browserify/browser"),
    "crypto": require.resolve("crypto-browserify"),
    "stream": require.resolve("stream-browserify"),
    "path": require.resolve("path-browserify"),
    fs: false
}
```
[Define plugin configuration](https://webpack.js.org/plugins/define-plugin/) so I can tell Webpack that a global variable named `Buffer` needs to exist

```javascript
{
    Buffer: ['buffer', 'Buffer'],
    process: 'process/browser',
}
```

I'm not saying all the libs above are used on the vrpc, but some for sure are, I would suggest having a strictly front-end section of the vrpc project so it can either load the browserfied versions of that code, or not use them all together.

Let me know if you need more comments.
